FROM openjdk:8 as build

WORKDIR /usr/src/app

COPY . .

RUN ./mvnw package

FROM openjdk:8-alpine

WORKDIR /usr/src/app

EXPOSE 8080

COPY --from=build /usr/src/app/target/docker-example-1.1.3.jar target/docker-example-1.1.3.jar

RUN adduser -D appuser

USER appuser

CMD ["java", "-jar", "./target/docker-example-1.1.3.jar"]
