FROM node:14 as build

WORKDIR /usr/src/app

COPY . .

RUN npm install && npm run build


FROM node:14-alpine

WORKDIR /usr/src/app

EXPOSE 5000

ENV REACT_APP_BACKEND_URL=http://localhost:8080

COPY --from=build /usr/src/app/build build

RUN npm install -g serve && adduser -D appuser

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]
